:reporttype:    Research Note TSSG-2012
:reporttitle:   What is WebRTC
:author:        Brendan O'Farrell
:email:         bofarrell@tssg.org
:group:         Telecommunications Software and Systems Group (TSSG)
:address:       Waterford Institute of Technology, West Campus, Carriganore, Waterford, Ireland
:revdate:       June 14, 2012
:revnumber:     N/A
:docdate:       June 14, 2012
:description:   A description of WebRTC.
:legal:         (C) Waterford Institute of Technology
:encoding:      iso-8859-1
:toc:



== What is WebRTC == 


"WebRTC is a free, open project that enables web browsers with Real-Time Communications (RTC) capabilities via simple Javascript APIs. The WebRTC components have been optimized to best serve this purpose."
http://webrtc.org[WebRTC]

WebRTC allows real time peer to peer audio visual communication via a HJTML5 compliant browser. Not all browsers have WebRTC  capability at present. At this time of writing both Google Chrome and Opera 12 have it available to test, Firefox will have it the 3rd-4th quater 2012 with Internet Explorer following in 2013. There are no plugins required for WebRTC to work and  no expensive pieces of hardware either. Just a WebRTC enabled browser, a camera (which is often quite standard on all new labtops), a mic/headset or mic/speakers and you real time communication availabe to you.

Having WebRtc integrated in a HTML5 enabled browser means you can now make real time audio video calls to any other WebRTC enabled device including such devices as  tablets, smart phones, e-readers etc. The quality of these calls are only limited by the quality of the hardware, the audio and video codecs  are open sourced and of a very high quality giving the client an excellent audio visual experience. 

With IEFT having set the standard for protocol and signalling, and W3C having set the standard for the API's for app developers, this means millions of Java Script developers can now deliever and define web based communication. No longer will it be the domain of the small number of SIP developers and VOIP system resellers. 

WebRTC has the potential for real change in how we communicate, much the same way the browser did for information. The effect can be that big. What we need is that all invested parties comply with the standards laid down by W3C and IEFT whether this comes to bear only time will tell. 
