:reporttype:    Research Note TSSG-2012
:reporttitle:   The organisations driving WebRTc
:author:        Brendan O'Farrell
:email:         bofarrell@tssg.org
:group:         Telecommunications Software and Systems Group (TSSG)
:address:       Waterford Institute of Technology, West Campus, Carriganore, Waterford, Ireland
:revdate:       July 03, 2012
:revnumber:     N/A
:docdate:       July 03, 2012
:description:   A look at the organisations behind WebRTc
:legal:         (C) Waterford Institute of Technology
:encoding:      iso-8859-1
:toc:


== Who are the organisations behind WebRTC 


There are number of companies involved in the WebRTC project in its present state. They are Google, Mozilla, Opera on the browser side with W3C and IEFT on the standards side. Only recently Microsoft have also shown an interest in this project but we are not expected to see any development from them until 2013 Having said that they are currently recruiting developers to work on a project combining Skype with WebRTC, so  development could occur earlier than expected.


 

=== IETF & W3C ===
The organisations which are responible for the WebRTC standards are IETF which is respobable for protocol and signalling and W3C which will look after the standards for API's for all app developers. We will take a more indept look at these organisations and there roles later in this document.
