:reporttype:    Research Note TSSG-2012
:reporttitle:   WebRTC
:author:        Brendan O'Farrell
:email:         bofarrell@tssg.org
:group:         Telecommunications Software and Systems Group (TSSG)
:address:       Waterford Institute of Technology, West Campus, Carriganore, Waterford, Ireland
:revdate:       June 14, 2012
:revnumber:     N/A
:docdate:       June 14, 2012
:description:   WebRTC Document
:legal:         (C) Waterford Institute of Technology
:encoding:      iso-8859-1
:toc:



== Introduction ==
An introduction to the subject.


== What is WebRTC  
WebRTC allows real time communication in the browser.  


== Who are the organisations behind WebRTC 
Google WebRTC +


== Who will set the standards for WebRTC 
W3C.IETF.


== What are the components of WebRTC 
Audio,Video,Network.


== How will it be deployed
Software/hardware


== How will WebRTC affect the Telecommunication industry 
Mobile, Skype. Positive/negative.


== What will the users experience be 
Wiil it be similar to the use of existing hadsets


== What market will it be developed for 
Personel, Commercial


== When can we expect its introduction 
2012/2103


== Who will benifit from it 
Networked commercial and professional


== Possible futher commercial benifits 
Health, Education, Gaming etc.



== Conclusion 

Up until now you could do anything in your browser except for real time video calling, of course you could use flash but flash is not available on all devices or platforms. WebRTC gives you real communication it will reduce the need for flash in the browser.

Allowing the audio and video codecs to be open sourced under a very lenient open source license has made it very attractive to place WebRTc into commercial products. With Google, Microsoft, Opera and Mozilla backing WebRTc it would seem that all is well in the browser world. But until all the standards have been set by W3C and IETF, and adapted by all interested parties we won't celebrate the dawn of a new communicationphase.

Aside from all the political posturing, WebRTC is here to stay. It will bring great innovation, vast commercial opportunities and most importantly real time communication for everyone.


 

 
 
 
