:reporttype:    Research Note TSSG-2012
:reporttitle:   The implications of WebRTC
:author:        Brendan O'Farrell
:email:         bofarrell@tssg.org
:group:         Telecommunications Software and Systems Group (TSSG)
:address:       Waterford Institute of Technology, West Campus, Carriganore, Waterford, Ireland
:revdate:       July 03, 2012
:revnumber:     N/A
:docdate:       July 03, 2012
:description:   The implications and benifits of having an open communications client on your browser.  
:legal:         (C) Waterford Institute of Technology
:encoding:      iso-8859-1
:toc:



== The implications and benifits of WebRTC ==
 
* Voice becomes just like all your other communications: organized into your preferred social or office tools. 
* As long as you're data connected, communications is in the cloud. People need only break out to PSTN (Public Switched Telephone Network) when the other person is not data connected, or the call quality is too low due to their Internet connection. The PSTN becomes the communications path of last resort.
* The company's website now becomes its call center front end. A weblog becomes your personal communications assistant.
* Communication service aggregators save customers running multiple clients on their phone; these would run in the cloud and be controlled from the browser.
* Click to call doesn't require an operator's voice network, just access to the Internet.
* Communications becomes like using any application on a smartphone; users can add features or capabilities or people throughout a call; e.g., N-way calling finally becomes simple and obvious with a simple point and swipe.
* New CRM (Customer Relationship Management) methods: click from email, from webpage, from app, from TV. The ability to communicate becomes embedded in most transactions.
* QoS (Quality of Service) remains an issue, but as the people using Vonage and Skype over the years will attest, QoS is rarely an insurmountable obstacle.
* Your phone number is no longer relevant anymore. It's a gateway to the past. Customers will only know the PSTN is involved because of the poor audio quality.
* Directory services become critical sources of value in connecting all the different IDs: telephone numbers, SIP IDs (IDentifier), web session IDs, other OTT (Over The Top) IDs (e.g. Skype name), etc.
* All the OTT communication applications e.g. Viber/Skype/Whatsapp can now be used everywhere: on your PC, smartphone, tablet, and TV. Breaking free from the app store allows them to explore new business models, just like the Financial Times did in breaking free of the app store in using HTML5.
* The new communication services that telcos are building on top of RCS (Rich Communication Services) will need to interoperate with the WebRTC world; currently WebRTC is a closed book to RCS.
* VAS (Value Added Services) leaves telco. Any web developer can create new communication services that deliver value and solve problems for customers. It the customer who will decide.
* Advertising finally enters the communications space, opening up business model innovation.
* Gaming becomes even more interesting, as any connected device with a camera can become a controller using gesture controls, as well as the more traditional methods for network-based games.http://www.nojitter.com/post/240001981/the-rise-of-webrtc-the-rules-of-communications-are-about-to-be-rewritten?pgno=3[Alan Quayle]
