:reporttype:    Research Note TSSG-2012
:reporttitle:   Google and WebRTC
:author:        Brendan O'Farrell
:email:         bofarrell@tssg.org
:group:         Telecommunications Software and Systems Group (TSSG)
:address:       Waterford Institute of Technology, West Campus, Carriganore, Waterford, Ireland
:revdate:       July 03, 2012
:revnumber:     N/A
:docdate:       July 03, 2012
:description:   Googles involvment with WebRTC
:legal:         (C) Waterford Institute of Technology
:encoding:      iso-8859-1
:toc:


== Google and WebRTC ==

Google have been to the forefront of this project. They want to develop a standard based real time media engine that will be available in all browsers. In order to drive the development of real time communication Google have released nearly $70 million worth of open source code to developers.  This open source audio and video codecs came about through the acquisition by Google of two companies in particular Global IP solutions and On2 Technologies. 

In early 2010, Google purchased On2, a technology company that developed the VP series of codecs, with the latest codec being VP8. On2 has always positioned its codecs as a patent free replacement to the H.26x series of codecs, which were standardized, patented and widely used in the communications and broadcast industry. Google then went about opening On2′s technologies to the world and open sourced VP8 under the name of the WebM project. The idea was to replace H.264 for web videos and by that, reduce patent costs for everyone, including Google themselves.

Also in  2010 acquired Google acquired another technology company, Global IP Solutions (GIPS), a company known for their media frameworks – a piece of technology that makes developing VoIP and video calling applications easier. At the time, GIPS had the largest market share in VoIP, which caused much of the telecommunications industry to search for alternative solutions as a valuable revenue source in SLA was disappearing. As with On2, Google took GIPS’ technology and open sourced it. This time they threw out all voice and video codecs that had patent owners and added an additional layer – a JavaScript API as an integration layer to web browsers. 

Why did Google seemingly dismiss the profitable patented codecs of both GIPS and On2? They wanted to have bidirectional media processing and coding technologies available in all browsers. By releasing the audio visual codecs royalty free they increased and set the pace for developing real time communication in all browsers. Google then proceeded to push it as a standard at the IETF and W3C. The IETF organisation is responsible for the protocol and signalling standards. W3C set the standards for the API’s.

Google host a forum page on the latest WebRTC developments at https://plus.google.com/113817074606039822053/posts[Google + WebRTC] 
